# Bookstore Backend Configuration
# bookstore:
#   backend-path: /api/**
#   backend-url: http://133.186.150.78:8083

# Bookstore Coupon Configuration
# bookstore:
#   coupon-path: /coupons/**
#   coupon-url: http://localhost:9494